### ISSUE TITLE
增加自动化部署功能

### ISSUE THREAD

**Issue by zhoujie16** [NascentCore/sxwl.ai#40]
我们的Web应用程序目前需要手动部署到生产环境中。每次手动部署需要花费大量时间和精力，而且容易出现人为失误和错误。
我建议增加自动化部署功能，以提高开发效率和减少错误，可以更好地管理和追踪部署过程，提高项目的可维护性和可扩展性。

有两种方案可以选择：一是使用Jenkins作为自动化部署工具，二是采用其他解决方案（例如Github Actions）。

**Comment by cairong-ai** [comment]
已增加 github actions 自动部署
