### ISSUE TITLE
【系统改进】主页上增加客服电话和客服 Email

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/sxwl.ai#46]
客服电话：15910236560
客服邮箱：help@sxwl.ai

**Comment by yzhao-2023** [comment]
![image](https://github.com/NascentCore/sxwl.ai/assets/142474494/b0b58eb5-65be-4433-a7dc-4c11138a4647)
![image](https://github.com/NascentCore/sxwl.ai/assets/142474494/3f05fe49-1457-43a8-965a-ec08d33be922)

**Comment by zhoujie16** [comment]
已修改
<img width="800" alt="截屏2023-12-01 00 26 39" src="https://github.com/NascentCore/sxwl.ai/assets/17493672/c3fd1a7d-13e5-4e3f-8619-615f5a7806d5">
