### ISSUE TITLE
【系统改进】提供一个文档，说明如何添加顶部 banner 信息

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/sxwl.ai#47]
![image](https://github.com/NascentCore/sxwl.ai/assets/142474494/6a60f901-4144-469b-81a6-48de40baed88)

参考 LambdaLabs 主页的设计，我们需要给普通成员一个指南，以便让他们可以快速更新这个 banner 广告
![image](https://github.com/NascentCore/sxwl.ai/assets/142474494/79e8d8a4-04f4-43ea-9582-f8e074f30d6e)

**Comment by zhoujie16** [comment]
顶部 banner 信息: 
修改：src/locales/en/index.ts  src/locales/zh/index.ts
headerBanner: 顶部banner文案
headerBannerLink: 顶部banner跳转链接，空白就是无链接

**Comment by zhoujie16** [comment]
顶部 banner 信息修改方式文档: src/locales/[README.md](http://readme.md/)
