### ISSUE TITLE
llm.sxwl.ai 添加文档和价格链接

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/sxwl.ai#51]
价格链接到 https://sxwl.ai/pricing/
文档链接到 https://sxwl.ai/docs/cloud/
如下图所示
![image](https://github.com/NascentCore/sxwl.ai/assets/142474494/2b99265a-0494-40e9-bc6b-168c535a0a06)

**Comment by zhoujie16** [comment]
已经修改 https://github.com/NascentCore/3k/pull/922
